FROM localhost/arcade-mame:latest

# Note: You need to download a MAME ROM and place it in the same directory as this Containerfile
# and replace "mamerom.zip" in this Containerfile and in retro_arcade.sh with the filename of the zip ROM file.
# 1. Copy your MAME ROM zip file
COPY mamerom.zip /opt/mame/roms/mamerom.zip

# 2. Autostart retroarch 
COPY --chmod=755 mame_arcade.sh /opt/arcade/mame_arcade.sh