FROM localhost/arcade-os:latest

# 1. Install EPEL 10 and Flatpak
# We replace the RPM Fusion setup with Flatpak and tools to download the core
RUN dnf install -y \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm \
    flatpak \
    wget \
    && dnf clean all

# 2. Configure Flathub and Install Mame
# We add the remote and install the application system-wide
# By default, Flatpak can't see /opt. We override this permission.

RUN flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y flathub org.mamedev.MAME && \
    flatpak override --filesystem=/opt/mame org.mamedev.MAME

# 3. Setup MAME directories for ROMS and config
RUN mkdir -p /opt/mame/roms /opt/arcade

# 4. Autostart script
COPY --chmod=755 mame_arcade.sh /opt/arcade/mame_arcade.sh

# 5. Populating autostart and applications for launching Arcade games
COPY --chmod=644 arcade_autostart.desktop /usr/share/arcade/arcade_autostart.desktop
COPY --chmod=644 mame.ini /usr/share/arcade/mame.ini
COPY tmpfiles.d/ /usr/lib/tmpfiles.d/
